services:
  api_painel-investimentos:
    image: ${DOCKER_REGISTRY-}api-painel-investimentos
    build:
      context: API_Painel-Investimentos
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "7717:8080"
      - "7718:8081"
    volumes:
      - ./API_Painel-Investimentos/SQLite:/app/SQLite